api/config/routes.rb
Rails.application.routes.draw do
  resources :thaughts
  resources :questions
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  #root to: "static#home"

  resources :sessions, only: [:create]
  resources :registrations, only: [:create]
  delete :logout, to: "sessions#logout"
  get :logged_in, to: "sessions#logged_in"

  resources :questions
end

api/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

api/app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user

  validates :question_text, presence: true
end

api/app/models/thaught.rb
class Thaught < ApplicationRecord
  belongs_to :user
  belongs_to :question
  validates :thought_text, presence: true
end

api/app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    validates_presence_of :email
    validates_uniqueness_of :email

    has_many :prompts
    has_many :thaughts
end

api/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    skip_before_action :verify_authenticity_token
end

api/app/controllers/concerns/current_user_concer.rb
module CurrentUserConcern
    extend ActiveSupport::Concern

    included do
        before_action :set_current_user
    end

    def set_current_user
        if session[:user_id]
            @current_user = User.find(session[:user_id])
        end
    end
end

api/app/controllers/concerns/static_controller.rb
class StaticController < ApplicationController
    def home
        render json: {status: "It's working"}
    end
end

api/app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: %i[ show edit update destroy ]
  before_action :authorized, except:  [:index, :show]

  # GET /questions or /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1 or /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions or /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to question_url(@question), notice: "Question was successfully created." }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1 or /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to question_url(@question), notice: "Question was successfully updated." }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1 or /questions/1.json
  def destroy
    @question.destroy

    respond_to do |format|
      format.html { redirect_to questions_url, notice: "Question was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def question_params
      params.require(:question).permit(:question_text, :user_id)
    end
end

api/app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
    def create
        user = User.create!(
            email: params['user']['email'],
            password: params['user']['password'],
            password_confirmation: params['user']['password_confirmation']
        )

        if user
            session[:user_id] = user.id
            render json: {
                status: :created,
                user: user
            }
        else
            render json: { status: 500 }
        end

    end
end

api/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    include CurrentUserConcern
    
    def create
        user = User.find_by(email: params["user"]["email"]).try(:authenticate, params["user"]["password"])

        if user
            session[:user_id] = user.id
            render json: {
                status: :created,
                logged_in: true,
                user: user
            }
        else
            render json: {status: 401 }
        end
    end

    def logged_in
        if @current_user
            render json: {
                logged_in: true,
                user: @current_user
            }
        else
            render json: {
                logged_in: false
            }
        end

    end

    def logout
        reset_session
        render json: {status: 200, looged_out: true }
    end

end

api/app/controllers/thaughts_controller.rb
class ThaughtsController < ApplicationController
  before_action :set_thaught, only: %i[ show edit update destroy ]
  before_action :authorized

  # GET /thaughts or /thaughts.json
  def index
    @thaughts = Thaught.all
  end

  # GET /thaughts/1 or /thaughts/1.json
  def show
  end

  # GET /thaughts/new
  def new
    @thaught = Thaught.new
  end

  # GET /thaughts/1/edit
  def edit
  end

  # POST /thaughts or /thaughts.json
  def create
    @thaught = Thaught.new(thaught_params)

    respond_to do |format|
      if @thaught.save
        format.html { redirect_to thaught_url(@thaught), notice: "Thaught was successfully created." }
        format.json { render :show, status: :created, location: @thaught }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @thaught.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /thaughts/1 or /thaughts/1.json
  def update
    respond_to do |format|
      if @thaught.update(thaught_params)
        format.html { redirect_to thaught_url(@thaught), notice: "Thaught was successfully updated." }
        format.json { render :show, status: :ok, location: @thaught }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @thaught.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /thaughts/1 or /thaughts/1.json
  def destroy
    @thaught.destroy

    respond_to do |format|
      format.html { redirect_to thaughts_url, notice: "Thaught was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_thaught
      @thaught = Thaught.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def thaught_params
      params.require(:thaught).permit(:thaught_text, :user_id, :question_id)
    end
end

api/app/helpers/application_helper.rb
module ApplicationHelper
end

api/app/helpers/questions_helper.rb
module QuestionsHelper
end

api/app/helpers/thaughts_helper.rb
module ThaughtsHelper
end

api/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Api</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

api/app/views/questions/_form.html.erb
<%= form_with(model: question) do |form| %>
  <% if question.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
        <% question.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :question_text, style: "display: block" %>
    <%= form.text_field :question_text %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

api/app/views/questions/_question.html.erb
<div id="<%= dom_id question %>">
  <p>
    <strong>Question text:</strong>
    <%= question.question_text %>
  </p>

  <p>
    <strong>User:</strong>
    <%= question.user_id %>
  </p>

</div>

api/app/views/questions/edit.html.erb
<h1>Editing question</h1>

<%= render "form", question: @question %>

<br>

<div>
  <%= link_to "Show this question", @question %> |
  <%= link_to "Back to questions", questions_path %>
</div>

api/app/views/questions/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Questions</h1>

<div id="questions">
  <% @questions.each do |question| %>
    <%= render question %>
    <p>
      <%= link_to "Show this question", question %>
    </p>
  <% end %>
</div>

<%= link_to "New question", new_question_path %>

api/app/views/questions/new.html.erb
<h1>New question</h1>

<%= render "form", question: @question %>

<br>

<div>
  <%= link_to "Back to questions", questions_path %>
</div>

api/app/views/questions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @question %>

<div>
  <%= link_to "Edit this question", edit_question_path(@question) %> |
  <%= link_to "Back to questions", questions_path %>

  <%= button_to "Destroy this question", @question, method: :delete %>
</div>

api/app/views/thaughts/_form.html.erb
<%= form_with(model: thaught) do |form| %>
  <% if thaught.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(thaught.errors.count, "error") %> prohibited this thaught from being saved:</h2>

      <ul>
        <% thaught.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :thaught_text, style: "display: block" %>
    <%= form.text_field :thaught_text %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :question_id, style: "display: block" %>
    <%= form.text_field :question_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

api/app/views/thaughts/_thaught.html.erb
<div id="<%= dom_id thaught %>">
  <p>
    <strong>Thaught text:</strong>
    <%= thaught.thaught_text %>
  </p>

  <p>
    <strong>User:</strong>
    <%= thaught.user_id %>
  </p>

  <p>
    <strong>Question:</strong>
    <%= thaught.question_id %>
  </p>

</div>

api/app/views/thaughts/edit.html.erb
<h1>Editing thaught</h1>

<%= render "form", thaught: @thaught %>

<br>

<div>
  <%= link_to "Show this thaught", @thaught %> |
  <%= link_to "Back to thaughts", thaughts_path %>
</div>

api/app/views/thaughts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Thaughts</h1>

<div id="thaughts">
  <% @thaughts.each do |thaught| %>
    <%= render thaught %>
    <p>
      <%= link_to "Show this thaught", thaught %>
    </p>
  <% end %>
</div>

<%= link_to "New thaught", new_thaught_path %>

api/app/views/thaughts/new.html.erb
<h1>New thaught</h1>

<%= render "form", thaught: @thaught %>

<br>

<div>
  <%= link_to "Back to thaughts", thaughts_path %>
</div>

api/app/views/thaughts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @thaught %>

<div>
  <%= link_to "Edit this thaught", edit_thaught_path(@thaught) %> |
  <%= link_to "Back to thaughts", thaughts_path %>

  <%= button_to "Destroy this thaught", @thaught, method: :delete %>
</div>